<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-42J99NO" failures="3" tests="22" name="Surefire test" time="48.576" errors="0" timestamp="2023-10-19T19:15:49 EEST">
  <testcase classname="weare.api.testing.comment.CreateCommentTest" name="createComment_Successful" time="0.966"/>
  <testcase classname="weare.api.testing.comment.DeleteCommentTest" name="deleteComment_Successful" time="1.583"/>
  <testcase classname="weare.api.testing.comment.EditCommentTest" name="editComment_Successful" time="1.246"/>
  <testcase classname="weare.api.testing.comment.FindAllCommentsTest" name="findAllComments_Successful" time="0.211">
    <failure type="java.lang.AssertionError" message="The array size is more than or equal to 1 expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The array size is more than or equal to 1 expected [true] but found [false]
at weare.api.testing.comment.FindAllCommentsTest.findAllComments_Successful(FindAllCommentsTest.java:33)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- findAllComments_Successful -->
  <testcase classname="weare.api.testing.comment.LikeDislikeCommentTest" name="likeDislikeComment_Successful" time="1.608"/>
  <testcase classname="weare.api.testing.connection.ApproveRequestTest" name="approveRequest_successful" time="0.226"/>
  <testcase classname="weare.api.testing.connection.GetUserRequestsTests" name="getUserRequestTest" time="0.483"/>
  <testcase classname="weare.api.testing.connection.SendRequestTest" name="sendRequest_successful" time="0.686"/>
  <testcase classname="weare.api.testing.post.CreatePostTest" name="createPost_Successful" time="0.975"/>
  <testcase classname="weare.api.testing.post.DeleteAPostTest" name="deletePost_Successful" time="1.692"/>
  <testcase classname="weare.api.testing.post.EditPostTest" name="editPost_Successful" time="0.514"/>
  <testcase classname="weare.api.testing.post.LikeDislikeAPostTest" name="likeAndDislikePost_Successful" time="1.823"/>
  <testcase classname="weare.api.testing.skill.CreateSkillTests" name="createSkill_Successful" time="0.32"/>
  <testcase classname="weare.api.testing.skill.DeleteSkillTests" name="deleteSkill_Successful" time="0.271"/>
  <testcase classname="weare.api.testing.skill.GetAllSkillsTests" name="newlyCreatedSkill_returned_whenGetAllSkills" time="0.229"/>
  <testcase classname="weare.api.testing.skill.GetOneSkillTests" name="getOneSkillById_Successful" time="0.231"/>
  <testcase classname="weare.api.testing.skill.UpdateSkillTests" name="updateSkill_Successful" time="0.273"/>
  <testcase classname="weare.api.testing.users.GetProfilePostsTests" name="getUserPosts_Successful" time="0.545"/>
  <testcase classname="weare.api.testing.users.GetUserByIdTests" name="getUserById_Successful" time="0.228">
    <failure type="java.lang.AssertionError" message="Incorrect status code. expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: Incorrect status code. expected [200] but found [404]
at base.BaseTestSetup.isResponse200(BaseTestSetup.java:52)
at weare.api.testing.users.GetUserByIdTests.getUserById_Successful(GetUserByIdTests.java:27)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- getUserById_Successful -->
  <testcase classname="weare.api.testing.users.GetUsersTests" name="getUsers_Successful" time="8.126"/>
  <testcase classname="weare.api.testing.users.RegisterUserTests" name="UserRegistration_When_InputValidData" time="0.599"/>
  <testcase classname="weare.api.testing.users.UpdateUserExpertiseTests" name="UserSuccessfullyUpdatesExpertise_When_ExpertiseChanged" time="0.619">
    <failure type="java.lang.AssertionError" message="Incorrect status code. expected [200] but found [500]">
      <![CDATA[java.lang.AssertionError: Incorrect status code. expected [200] but found [500]
at base.BaseTestSetup.isResponse200(BaseTestSetup.java:52)
at weare.api.testing.users.UpdateUserExpertiseTests.UserSuccessfullyUpdatesExpertise_When_ExpertiseChanged(UpdateUserExpertiseTests.java:33)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- UserSuccessfullyUpdatesExpertise_When_ExpertiseChanged -->
</testsuite> <!-- Surefire test -->
