<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite name="Failed suite [Surefire suite]" verbose="0">
  <test thread-count="5" name="Surefire test(failed)" verbose="0">
    <classes>
      <class name="weare.api.testing.users.GetUserByIdTests">
        <methods>
          <include name="setup"/>
          <include name="setupClass"/>
          <include name="getUserById_Successful"/>
        </methods>
      </class> <!-- weare.api.testing.users.GetUserByIdTests -->
      <class name="weare.api.testing.users.UpdateUserExpertiseTests">
        <methods>
          <include name="UserSuccessfullyUpdatesExpertise_When_ExpertiseChanged"/>
          <include name="setup"/>
          <include name="setupClass"/>
        </methods>
      </class> <!-- weare.api.testing.users.UpdateUserExpertiseTests -->
      <class name="weare.api.testing.comment.FindAllCommentsTest">
        <methods>
          <include name="findAllComments_Successful"/>
          <include name="setup"/>
        </methods>
      </class> <!-- weare.api.testing.comment.FindAllCommentsTest -->
    </classes>
  </test> <!-- Surefire test(failed) -->
</suite> <!-- Failed suite [Surefire suite] -->
